test_file: ['/content/drive/MyDrive/fyp-dataset/dataset/refcoco/test/refcoco/test_dataset.json']
image_root: '/content/drive/MyDrive/fyp-dataset/test_images/'
refcoco_data: '/content/drive/MyDrive/fyp-dataset/dataset/refcoco/test/'
vlue_test: False


## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: '/content/drive/MyDrive/fyp-dataset/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size: 20
max_tokens: 40
careful_hflip: False  # first check whether 'left' or 'right' in captions






