train_file: ['content/drive/MyDrive/fyp-dataset/dataset/train_dataset.json']
test_file: ['data/finetune/refcoco+_val.json','data/finetune/refcoco+_test.json']

refcoco_data: 'content/drive/MyDrive/fyp-dataset/'
det_file: 'data/finetune/refcoco+/dets.json'
coco_file: 'content/drive/MyDrive/fyp-dataset/dataset/cocos.json'
careful_hflip: False

image_root: 'content/drive/MyDrive/fyp-dataset/images/'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size: 20
max_tokens: 40


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}







